#!/usr/bin/env python
# coding=utf-8

import sys
import client.protocol as proc
import os
import subprocess

pid = str(os.getpid());

def debug(*args):
    sys.stderr.write(pid+":"+' '.join(map(str,args)) + '\n')

proc.write_msg(sys.stdout, "helo v=1.0.0");

incoming = []

while True:

    msg = proc.read_msg(sys.stdin)
    
    if msg.msg == 'ok':
        debug("ok")
        break
    elif msg.msg == 'push':
        debug("push")
        incoming.append(proc.Push._make(msg.params))
    else:
        debug("error")
        proc.write_msg(sys.stdout, "error")
        sys.exit(1)

proc.write_msg(sys.stdout, "accept");

for push in incoming:
    debug("incoming "+push.package)
    proc.read_file(sys.stdin, push.package+"-"+push.hash+".pack", push.hash)
    subprocess.call(["armory-repo", "--yes", "push", "--remove", push.package+"-"+push.hash+".pack"])